name: Automated API tests For Education and E-learning

on: 
  workflow_dispatch:
  push:

jobs:
  collection-1:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/osx_64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests for Collection 1
        run: |
          postman collection run "33081408-b0ba9ee4-0bca-4bc9-9718-bea2f0f5bbc2" -e "33081408-3e2a1df8-1070-4764-8fa5-a9bda92d3a0e"
      - name: Logout from Postman CLI
        run: postman logout --with-api-key ${{ secrets.POSTMAN_API_KEY }}

  
